apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 709794902769.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 709794902769.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: "77123907"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
